version: '2'
networks:
  proyecto:
services:
  cassandra_node-1:
    container_name: cassandra_node-1
    hostname: cass1
    networks:
      - proyecto
    image: cassandra:latest
    ports:
      - 9042:9042
    environment: &environment
      - CASSANDRA_SEEDS= cassandra_node-1, cassandra_node-2
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  
  cassandra_node-2:
    container_name: cassandra_node-2
    hostname: cass2
    networks:
      - proyecto
    image: cassandra:latest
    ports:
      - 9043:9042
    environment:
      - CASSANDRA_SEEDS= cassandra_node-1, cassandra_node-2
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    depends_on:
      - cassandra_node-1